tasks:
  - name: drupal
    before: curl -fsSL https://get.docksal.io | bash
    init: |
      cp .gitpod/templates/* .docksal/.
      fin init
    command: |
      fin start
      gp preview $(gp url 8080)

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - andrewdavidblum.drupal-smart-snippets

    # Twig extensions.
    - mblode.twig-language-2

    # Bash extensions.
    - timonwong.shellcheck
    - rogalmic.bash-debug


ports:
  # Used by JS projects
  - port: 3000
    onOpen: ignore
# local db clients
  - port: 3306
    name: Database
    onOpen: ignore
# Used by JS projects
  - port: 5000
    onOpen: ignore
# Used by Storybook
  - port: 6057
    name: Storybook
    onOpen: ignore
# Used by MailHog
  - port: 8027
    name: MailHog
    onOpen: ignore
# Used by phpMyAdmin
  - port: 8036
    name: phpMyAdmin
    onOpen: ignore
  - port: 8080
    name: website
    onOpen: ignore
# Ignore host https port
  - port: 8443
    name: (not used)
    onOpen: ignore
# xdebug port
  - port: 9003
    name: xdebug
    description: xdebug
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
